### ISSUE TITLE
Plugin doesn't work on Firefox

### ISSUE THREAD

**Issue by mountpoint** [chenjuneking/quill-image-drop-and-paste#42] opened 2022-09-20 12:45 UTC
The plugin doesn't work on Firefox. 

`handler` doesn't call at all

For testing just run [this example](https://github.com/chenjuneking/quill-image-drop-and-paste/tree/master/example/script-demo) on latest Firefox.

I've tested it on Firefox on Debian, and Firefox on Windows 10

**Comment by chenjuneking** [comment] 2022-09-21 07:08
Hi, @mountpoint .
I'd tested on Firefox(v105.0 64 bit) on Windows 11, it's working fine.
![image](https://user-images.githubusercontent.com/4432938/191437446-b80a6ee6-f876-40a2-916f-945ef985dd90.png)


Could apply more details about this issue?

**Comment by chenjuneking** [comment] 2022-09-21 07:08
Hi, @mountpoint .
I'd tested on Firefox(v105.0 64 bit) on Windows 11, it's working fine.
![image](https://user-images.githubusercontent.com/4432938/191437446-b80a6ee6-f876-40a2-916f-945ef985dd90.png)


Could apply more details about this issue?

**Comment by mountpoint** [comment] 2022-09-21 08:00
Hi @chenjuneking ! Sure, I'll provide some screenshots

**First screenshot** is from latest Google Chrome (Debian). Everything works great.

![2022-09-21_10-51](https://user-images.githubusercontent.com/2649412/191447670-ac230ccf-5040-403f-86bb-c1e81d740331.png)

**Second screenshot** is from latest Firefox 105.0 (64-bit) (Debian). Look at the image. It inserts into editor area. And I don't see any logs in console

![2](https://user-images.githubusercontent.com/2649412/191448003-dd9bc481-cd2b-4d58-a556-8b2a32c89af2.png)

Also I use your plugin in my project and there are same troubles. Same troubles on Firefox on Windows 10.

If you have possibility, check it on Windows 10

**Comment by chenjuneking** [comment] 2022-09-22 03:01
Hi @mountpoint . Thanks for the details and I feel sorry for your trouble.
Since I was not able to get another Windows 10 device. I'd simulated a `debian x64 + firefox v105.0` and `windows 10 + firefox v105.0` environment by VirtualBox on my laptop(windows 11), but they are working fine.

![image](https://user-images.githubusercontent.com/4432938/191645780-ff4e5a4b-7bbe-4c42-b202-dc2634a81d3f.png)
![image](https://user-images.githubusercontent.com/4432938/191646338-d7df80d1-2935-4672-a476-8f910a8ce36e.png)

I‘ll keep tracking this issue and fix it when I could reproduce the problem.

**Comment by mountpoint** [comment] 2022-09-22 14:19
@chenjuneking thanks for your response! I will check it on another devices. Maybe this is something strange with my devices :smile:

**Comment by rahultrivedi180** [comment] 2022-10-17 04:54
@mountpoint any updates?

**Comment by mountpoint** [comment] 2022-10-17 05:12
@rahultrivedi180 aaahhh, I forgot to check it on my colleague's devices. Do you have the same problem?

**Comment by rahultrivedi180** [comment] 2022-10-17 05:16
> @rahultrivedi180 aaahhh, I forgot to check it on my colleague's devices. Do you have the same problem?

Nope. Didn't try this package yet. I'm about to try in the next couple of days

**Comment by chenjuneking** [comment] 2023-05-05 01:40
Since there's no more feedback, I'll close this issue.

**Closed as completed by chenjuneking** 2023-05-05 01:40 UTC
